global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['app:8000']   # nome service nel compose

  - job_name: 'airflow_drift'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']   # raccoglie metriche pushate dai task Airflow
